name: weblounge
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebc232'
    - '#ffffff'
    - '#000000'
    - '#48474d'
    - '#afadb2'
  brandStrength: 0.75
  lightness: 0.33587506343610585
  saturation: 0.3889309260994196
  rhythmicContrast: 0.756006094859913
purpose: []
